module CirclesHelper
  def get_image(circle_number)
    case circle_number
	when "1"
	  return "knot1.png"
	when "2"
	  return "knot2.png"
	when "3"
	  return "knot3.png"
	when "4"
	  return "knot4.png"
	when "5"
	  return "knot5.png"
	when "6"
	  return "knot6.png"
	when "7"
	  return "knot7.png"
	when "8"
	  return "knot8.png"
	when "9"
	  return "knot9.png"
	when "10"
	  return "knot10.png"
	when "11"
	  return "knot11.png"
	when "12"
	  return "knot12.png"
	when "13"
	  return "knot13.png"
	when "14"
	  return "knot14.png"
	when "15"
	  return "knot15.png"
	when "16"
	  return "knot16.png"
	when "17"
	  return "knot17.png"
	when "18"
	  return "knot18.png"
	when "19"
	  return "knot19.png"
	when "20"
	  return "knot20.png"
	when "21"
	  return "knot21.png"
	when "22"
	  return "knot22.png"
	when "23"
	  return "knot23.png"
	when "24"
	  return "knot24.png"
	when "25"
	  return "knot25.png"
	when "26"
	  return "knot26.png"
	when "27"
	  return "knot27.png"
	when "28"
	  return "knot28.png"
	when "29"
	  return "knot29.png"
	when "30"
	  return "knot30.png"
	when "31"
	  return "knot31.png"
	when "32"
	  return "knot32.png"
	when "33"
	  return "knot33.png"
	when "34"
	  return "knot34.png"
	when "35"
	  return "knot35.png"
	when "36"
	  return "knot36.png"
	when "37"
	  return "knot37.png"
	when "38"
	  return "knot38.png"
	when "39"
	  return "knot39.png"
	when "40"
	  return "knot40.png"
	when "41"
	  return "knot41.png"
	when "42"
	  return "knot42.png"
	when "43"
	  return "knot43.png"
	when "44"
	  return "knot44.png"
	when "45"
	  return "knot45.png"
	when "46"
	  return "knot46.png"
	when "47"
	  return "knot47.png"
	when "48"
	  return "knot48.png"
	when "49"
	  return "knot49.png"
	when "50"
	  return "knot50.png"	  
	end
  end
 
  def get_header_text(circle_number)
    case circle_number
	  when "1"
	    return "Create Hand Painted Coffee Mugs for Each Other!"
	  when "2"
	    return "Build an Awesome Lego Model!"
	  when "3"
	    return "Plant a Tree!"
	  when "4"
	    return "Talk to a Banker About Getting on Track to Buy a Home!"
	  when "5"
	    return "Tie all of the Knots!"
	  when "6"
	    return "Attend a Charity Event!"
	  when "7"
	    return "Hike Three New Locations!"
	  when "8"
	    return "Do Some Wedding Research by Watching 3 Wedding Movies!"
	  when "9"
	    return "Go Hunting Together!"
	  when "10"
	    return "Cook a Foreign Meal From Scratch!"
	  when "11"
	    return "Visit the Grand Canyon!"
	  when "12"
	    return "Stay in a Hotel with an Interesting Theme!"
	  when "13"
	    return "Visit 10 Different Micro Breweries!"
	  when "14"
	    return "Go Horseback Riding!"
	  when "15"
	    return "Attend 5 Concerts!"
	  when "16"
	    return "Go Apple Picking in Julian and Make a Pie With the Haul!"
	  when "17"
	    return "Get a Couple Massage!"
	  when "18"
	    return "Take a Dance Class!"
	  when "19"
	    return "Watch the Sun Rise and Set in the Same Day!"
	  when "20"
	    return "Complete the 30 Day Yoga Challenge!"
	  when "21"
	    return "Get Photos Taken in 10 Different Photo-booths!"
	  when "22"
	    return "Go on a Picnic!"
	  when "23"
	    return "Go Whale Watching!"
	  when "24"
	    return "See a Show at Medieval Times!"
	  when "25"
	    return "Watch a Play at the Old Globe!"
	  when "26"
	    return "Co-op the Gears of Wars Series!"
	  when "27"
	    return "Enjoy a Day Together With No Electronic Devices!"
	  when "28"
	    return "Visit 5 Local Coffee Shops!"
	  when "29"
	    return "Each Select and Read a Book, Swap and Read Theirs!"
	  when "30"
	    return "Take an Advanced Shooting Class!"
	  when "31"
	    return "Go Paddleboarding!"
	  when "32"
	    return "Catch Some Fish or Lobster!"
	  when "33"
	    return "See 5 Movies in Different Locations!"
	  when "34"
	    return "Spend a Whole Day Spoiling Indianna!"
	  when "35"
	    return "Flight Roulette - Go to the Airport, Buy Random Tickets and Leave!"
	  when "36"
	    return "Take a course in French, Trying To Improve Our Fluency!"
	  when "37"
	    return "Get a Good Start on Bug Out Bags!"
	  when "38"
	    return "Enjoy a Five Course Dinner in Stages at 5 Restaurants!"
	  when "39"
	    return "Build a New Night Stand!"
	  when "40"
	    return "Each of us Plan and Execute a Mystery Date for the Other!"
	  when "41"
	    return "Take a Sausage Making or Butchering Class!"
	  when "42"
	    return "Go Out and Tour 3 Places!"
	  when "43"
	    return "Visit 10 Farmer's Markets!"
	  when "44"
	    return "Go to a Burlesque Show!"
	  when "45"
	    return "Share 5 Meals Created Using Herbs from a Garden We Grow!"
	  when "46"
	    return "Share New Restaurant Fridays with 15 Different People!"
	  when "47"
	    return "Partake in a Meatless Fortnight!"
	  when "48"
	    return "Complete a Half Marathon Together!"
	  when "49"
	    return "Host a Bridal Party Royale!"
	  when "50"
	    return "Craft and Send Out Save the Dates!"	  
    end
  end

  def get_body_headline_text(circle_number)
    case circle_number
	  when "1"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "2"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "3"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "4"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "5"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "6"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "7"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "8"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "9"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "10"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "11"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "12"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "13"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "14"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "15"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "16"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "17"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "18"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "19"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "20"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "21"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "22"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "23"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "24"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "25"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "26"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "27"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "28"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "29"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "30"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "31"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "32"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "33"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "34"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "35"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "36"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "37"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "38"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "39"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "40"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "41"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "42"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "43"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "44"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "45"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "46"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "47"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "48"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "49"
	    return "This Knot List item is in the works! More info is coming soon!"
	  when "50"
	    return "This Knot List item is in the works! More info is coming soon!"		
	end  
  end
end